#!/bin/bash -l

#$ -cwd
#$ -P bf528
#$ -j y
#$ -pe mpi_16_tasks_per_node 16
#$ -l h_rt=48:00:00

source /etc/bashrc
module load cufflinks

P0BAM= /projectnb2/bf528/students/rkafrawi/Project_2_Real/part_4/P0_1_tophat_real/accepted_hits.bam  # put the full path to your accepted_hits.bam file here

SAMPLEDIR=/project/bf528/project_2/data/samples/
P0REPS=$P0BAM,$SAMPLEDIR/P0_2/accepted_hits.bam
ADREPS=$SAMPLEDIR/Ad_1/accepted_hits.bam,$SAMPLEDIR/Ad_2/accepted_hits.bam

LABEL="P0,Ad"
OUTDIR=cuffdiff_out_real
FASTA=/project/bf528/project_2/reference/mm9.fa

cuffdiff -p 16 -L $LABEL -u -b $FASTA -o $OUTDIR $SAMPLEDIR/merged_asm/merged.gtf $P0REPS $ADREPS
